swagger: 2.0.0
openapi: 3.1.0
info:
  title: 24h du Mans - API
  description: >-
    Notre API met à votre disposition un trésor de données sur la plus célèbre
    course d'endurance au monde.
  version: 1.0.0
servers:
  - url: http://localhost:4629/
    description: Environnement de développement
paths: {}
components: {}
tags: []
